### ISSUE TITLE
Not visible with light mode

### ISSUE THREAD

**Issue by hemthead** [NotALakeLurk/De-militarized_time#2]
This used to work, so I'm not really sure what happened... anyway, pretty self explanatory; the text is not visible on "light-mode".

**Comment by hemthead** [comment]
This also does not seem to be a problem with devices where `prefers-color-scheme` evaluates to `no-preference` is true (my watch).

**Comment by loki1205** [comment]
Hi, I am interested to solve this. Can you assign this to me?

**Comment by OscarTopliss** [comment]
Hello! I think the problem comes from the script not checking the theme again after it starts running, so when changing the theme with the window open, the text doesn't update. I tried making a themeUpdate function which is then called in the main loop, which seems to work. Most websites I saw seemed to suggest using an EventListener, but I'm not comfortable enough with JS to understand how to implement that.

**Comment by OscarTopliss** [comment]
> Hi, I am interested to solve this. Can you assign this to me?
Hi @loki1205 ! I apologise, I didn't see any replies on this when I started working on it.

**Comment by loki1205** [comment]
No problem. However I am comfortable with JS, if you need any further help let me know. Thank you!

**Comment by NotALakeLurk** [comment]
I am an actual idiot... you just have to refresh the page first lol.
